baseurl = "https://example.org/"
languageCode = "en-us"
title = "Elie Hymowitz"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Elie Hymowitz"
	description = "Welcome to my webzone! I post what I make here"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "<p> <strong>I'm Elie!</strong> I make music and things </p>"
		# The icons will be shown if you enter your username
		facebook = "Eliehymowitz"
    instagram = "elie.s.h"
		linkedin = "eliehymowitz"
		github = "ehymowitz"

	[params.about]
	#see layouts/partials/about for content
		hide  = false
		title1 = "Upcoming Shows"
		content = ""
		title2 = "Video Links"
		title3 = "Instragram Solos"



	[params.portfolio]
		hide  = false
		title = "Photos"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/Frosh1Full.jpg"
			thumb = "thumbs/Frosh1Thumb.jpg"
			title = ""
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/Frosh2Full.jpg"
			thumb = "thumbs/Frosh2Thumb.jpg"
			title = ""
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/LogifemFull.jpg"
			thumb = "thumbs/LogifemThumb.jpg"
			title = ""
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/OutsideFull.jpg"
			thumb = "thumbs/OutsideThumb.jpg"
			title = ""
			description = ""

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit "

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "ehymowitz@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Music"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Things"
	url  = "post/things"
	weight = 15

[[menu.main]]
	name = "Photos/Videos"
	url = "post/photovid"
	weight = 20

[[menu.main]]
	name = "About Me"
	url  = "post/about"
	weight = 25

[[menu.main]]
	name = "Resume"
	url = "post/resume"
	weight = 30
